from .offensive_words import detect_offensive_words
from .atleast_one_http_link import detect_atleast_one_http_link
from .invalid_ssl_cert import detect_atleast_one_invalid_ssl_link
from .phishing_links import detect_phishing_links
from .malicious_links import detect_malicious_links
